### ISSUE TITLE
Can not change resolution on Ubuntu VNC

### ISSUE THREAD

**Issue by cracker0dks** [ConSol/docker-headless-vnc-container#1]
Centos working fine.
On Ubuntu I get: 
![image](https://cloud.githubusercontent.com/assets/1816621/16717872/6d82dffe-471b-11e6-87da-4f9e11bfd982.png)

And all possible resolutions are:
![image](https://cloud.githubusercontent.com/assets/1816621/16717950/8d8c02f8-471b-11e6-80ab-82c1b4d39668.png)

How to change resolution on Ubuntu?

**Comment by toschneck** [comment]
For changing the resolution you can override the environment variable `VNC_RESOLUTION`.
Like `docker run -e VNC_RESOLUTION=1024x768 -p 5901:5901 -p 6901:6901 consol/ubuntu-xfce-vnc`.

Furthermore I tested the randr error, but didn't get this error. Maybe you have refresh your docker image via `consol/ubuntu-xfce-vnc`. If the problem is solved, please close this issue ;-)

**Comment by cracker0dks** [comment]
ah that worked! thanks :)

**Comment by r1sknt** [comment]
Can we change the resolution while the container running?
