### ISSUE TITLE
issue with vnc on ubuntu

### ISSUE THREAD

**Issue by nckro** [ConSol/docker-headless-vnc-container#13]
Hi, beginner docker enthusiast here. I have a dumb question. If someone can shed some light on this issue it would be awesome. I want to add qt to this vnc image. I tried manually, starting a container with ubuntu-xfce-vnc, logging via vnc and then installing qt from the website. And vnc works + qt. I then commited the changes to another image (test_image). The issue is when i start a new container from my new image of vnc+qt (test_image), vnc doesn't work anymore and i have no ideea why. I thought it was something with qt, but it seems even if i do just a apt-get update and install a simple packet, like nano/ping/etc ... and commit changes, vnc doesnt work in the new container. Any idea? Am I doing something wrong? Thanks in advance

**Comment by toschneck** [comment]
Hi @nckro,
I think the problem here is, that you will use the `docker commit` command to generate a new image. The correct way is in general to wirte a separate new `Dockerfile` where you install new software, like we did it in this Dockerfile: https://github.com/ConSol/sakuli/blob/master/docker/sakuli-ubuntu-xfce/Dockerfile

After you written your custom Dockerfile you can build it like follow:
```.bash
docker build -t your-user/new-image-name <path-to-Dockerfile-location>
```

**Comment by nckro** [comment]
Hi @toschneck,
Thank you very much for your response. I also found out where was the problem with the vnc in the generated image. The startup scripts start novnc and vnc on display:1, when i generated the image manually i forgot to empty /tmp and there was a vnc lock file which prevented this. I learned today that it is a good thing to empty /tmp and /var/apt/lib before commiting to a new image.

This issue can be closed.
Thanks
