### ISSUE TITLE
Empty blue screen when access from remote host 

### ISSUE THREAD

**Issue by gizbo** [ConSol/docker-headless-vnc-container#175]
**Image**
ghcr.io/consol/docker-headless-vnc-container/rocky-xfce-vnc
**Tag**
latest/nightly
**Short overview**
Empty blue screen when access from remote host 
**Detailed error description**
Getting a empty blue screen when access from remote host but working fine when access locally. Other image debian-xfce works fine remote/local
thanks

**Comment by sni** [comment]
Seems like something got mixed up. This is icewm and that's how icewm looks. It's a very minimalistiv window manager. You should still see a menu when clicking the right mouse button anywhere.
The mixup might be fixed with 894d7946fa7cc14628253b8a4ac0aadeab5c7c7a. Other than that i don't see an issue here.
