### ISSUE TITLE
How to create a login window

### ISSUE THREAD

**Issue by jmarcio** [ConSol/docker-headless-vnc-container#34]
Hello,
Very interesting software. Thanks for sharing it.
I'd like to be able to have a login window, before falling directly to the desktop. In other words, I'd like to put this docker in a server and let multiple users connect to the docker.
Any hint ?
Thanks

**Comment by toschneck** [comment]
I don't think that you can implement in a Docker container multiple Users. In my opinion it doesn't make sense, because therefore you will use a classic virtual machine. If you wan't to have different sessions, just start multiple containers with different passwords. See https://github.com/ConSol/docker-headless-vnc-container#31-example-override-the-vnc-password
