### ISSUE TITLE
How to only use the web way without vnc and without xfce?

### ISSUE THREAD

**Issue by guotong1988** [ConSol/docker-headless-vnc-container#49]
I want to install cuda in your docker image. 
The error shows that the running X server stops the installation.
Thank you very much !
@toschneck

**Comment by guotong1988** [comment]
https://github.com/novnc/noVNC/issues/868

**Comment by guotong1988** [comment]
but the solution above is only 51M

**Comment by toschneck** [comment]
I think the problem is that CUDA need a real graphic engine accessible or other drivers then the pure x-server. Maybe the image from Nvidia would help you out there. See https://gitlab.com/nvidia/cuda/blob/ubuntu16.04/9.0/base/Dockerfile.

If you want to use our image together, I would fork this repo and change the base image of [`Dockerfile.ubuntu.xfce.vnc`](https://github.com/ConSol/docker-headless-vnc-container/blob/master/Dockerfile.ubuntu.xfce.vnc) from `ubuntu:16.04` to one of them [nvidia/cuda/tags](https://hub.docker.com/r/nvidia/cuda/tags/)  like `9.0-runtime-ubuntu16.04`:
```Dockerfile
# This Dockerfile is used to build an headles vnc image based on Ubuntu

# remove FROM ubuntu:16.04
FROM 9.0-runtime-ubuntu16.04
....
```
