### ISSUE TITLE
Help - nginx proxy_pass config

### ISSUE THREAD

**Issue by thefoxman88** [ConSol/docker-headless-vnc-container#58]
Hey!
Looking for advice on how to config nginx reverse proxy with this docker. Some elements are not loading, as I only get "Loading" for the main window and buttons like "Send CtrlAltDel", "Shutdown", "Reboot", and "reset"

`
        location /chrome {
                include /config/nginx/proxy.conf;
                proxy_pass http://192.168.0.100:8092/;
        }
`

Note: This isn't a real "issue" with the software, just more I am out of option. Currently reading up on nginx options to get the missing parts passed through but hoping someone with more knowledge has already figured it out.

**Comment by toschneck** [comment]
I don't know why you have the need for a reverse proxy, you can also map the port on the container startup to a open port like `docker run  -p 80:6901 ...` then you get access to the container via `your-host-ip:80` ?

Due to the fact that I never configured a reverse proxy, I can't help you on this, maybe the [noVNC](https://github.com/novnc/noVNC) Projektpage can hep you there more
