### ISSUE TITLE
Question on browser add-ins such as video players

### ISSUE THREAD

**Issue by mgrollman** [ConSol/docker-headless-vnc-container#60]
consol/centos-xfce-vnc has been a very helpful testing tool for us.  We have a test case the requires Firefox 46 in the container to have access to a video player add-in or setting change of some kind.   I am pretty green with Docker, but am wondering if others might have had a similar need in the past, and how they would tweak your Dockerfile to add this functionality to the build.  Thanks! - Michael

**Comment by toschneck** [comment]
@mgrollman  great to heart that you like our project. To your question 
like at [Extend a Image with your own software](https://github.com/ConSol/docker-headless-vnc-container#1-extend-a-image-with-your-own-software) you can modify our basic image like described there. 
Due to the fact that the yum repository don't contain all firefox version you can use our installer script [firefox.sh](https://github.com/ConSol/docker-headless-vnc-container/blob/master/src/common/install/firefox.sh). The available Firefox versions can be  found under: http://releases.mozilla.org/pub/firefox/releases/
