### ISSUE TITLE
is there any way to get sound to work?

### ISSUE THREAD

**Issue by ncresswell** [ConSol/docker-headless-vnc-container#77]
The Pulse Audio Volume menu item just sits forever at "connecting to Pulse audio"

**Comment by toschneck** [comment]
@ncresswell I can't provide currently a definitive way, but it should be possible. The normal way should be to mount the soundsystem of the host system. Like @jessfraz does there  https://github.com/jessfraz/dockerfiles/blob/master/chromium/Dockerfile.

Due to my currently limited time you can just start at this point and try to get it work by your own ...

    docker run --privileged -it -p 6901:6901 -u 0 --device /dev/snd:/dev/snd consol/ubuntu-xfce-vnc bash

**Comment by yonixw** [comment]
All I had to do is to run "pulseaudio" from root (my docker run root user) and it started. I had some errors in console but everything worked.

Note: in my journy I had to `apt install` those libs: ` libportaudio2  pulseaudio jackd2 alsa-utils dbus-x11` so I dont know if they affected results or not.

![image](https://user-images.githubusercontent.com/5826209/96155514-aeba2a80-0f18-11eb-9aeb-a98643c4e7d3.png)
